export const SET_CONVERTED_CURRENCY = "SET_CONVERTED_CURRENCY";
export const SET_IS_CONVERT_ERROR = "SET_IS_CONVERT_ERROR";

export const SET_RATES = "SET_RATES";
export const SET_IS_RATES_ERROR = "SET_IS_RATES_ERROR";

export const GET_CONVERTED_CURRENCY = "GET_CONVERTED_CURRENCY";
export const GET_CURRENCY_RATES = "GET_CURRENCY_RATES";
